Script started on Wed 18 Jan 2023 04:11:42 PM CST
[root@localhost ~]# cd ~
[root@localhost ~]# pwd
/root
[root@localhost ~]# ls
commands.script  [0m[01;32mexamplescript.sh[0m
[root@localhost ~]# echo exm[Kamplescript.sh is [K[K[K[K[K[K[K[K[K[K[K[K[K[Kesc[K[K[K[K[K[K[K[K[K[K[K[K[K[Kmkdir newdir
[root@localhost ~]# touch newfile.txt
[root@localhost ~]# cp newfile.txt  new[K[K[K[K[K newdir
[root@localhost ~]# cd newdir/
[root@localhost newdir]# ls
newfile.txt
[root@localhost newdir]# cd ..
[root@localhost ~]# mv newfile.txt newfilerenamed.txt
[root@localhost ~]# mv newfilerenamed.txt new
newdir/             newfilerenamed.txt  
[root@localhost ~]# mv newfilerenamed.txt newdir/
[root@localhost ~]# mv newdir/newfile.txt .
[root@localhost ~]# rm newdir [K[K[K[K[K[K[Kf [K[K-f newdir/ -r
[root@localhost ~]# rm -f newfile.txt 
[root@localhost ~]# mkdir emptydir
[root@localhost ~]# rmdir emptydir/
[root@localhost ~]# chmod [K[K[K[K[K[Kchmod +x examplescript.sh 
[root@localhost ~]# ./examplescript.sh 
Script is executable!
[root@localhost ~]# who
root     tty1         2023-01-18 15:54
root     pts/0        2023-01-18 16:11
[root@localhost ~]# nproc
4
[root@localhost ~]# echo I've[K[K[K[KI have left the[K[K[Kany terminal graphics applications [K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kman and top last, as the man page for script says these program [A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K[K[K[K[K[K[K[K[Kse or[K[K[K types o f preogr[K[K[K[Kograms mess with the outputted script file. If this[Kngs do not look right in the file, this is why .
I have left man and top last, as the man page for script says these types of programs mess with the outputted script file. If things do not look right in the file, this is why.
[root@localhost ~]# man man
MAN(1)                                  Manual pager utils                                 MAN(1)[m
[m
[1mNAME[0m[m
       man - an interface to the on-line reference manuals[m
[m
[1mSYNOPSIS[0m[m
       [1mman[0m  [[1m-C[0m  [4mfile[24m]  [[1m-d[0m]  [[1m-D[0m]  [[1m--warnings[0m[=[4mwarnings[24m]]  [[1m-R[0m  [4mencoding[24m]  [[1m-L[0m [4mlocale[24m] [[1m-m[0m [4msys‐[24m[m
       [4mtem[24m[,...]] [[1m-M[0m [4mpath[24m] [[1m-S[0m [4mlist[24m] [[1m-e[0m [4mextension[24m] [[1m-i[0m|[1m-I[0m] [[1m--regex[0m|[1m--wildcard[0m]  [[1m--names-only[0m][m
       [[1m-a[0m]  [[1m-u[0m]  [[1m--no-subpages[0m]  [[1m-P[0m  [4mpager[24m] [[1m-r[0m [4mprompt[24m] [[1m-7[0m] [[1m-E[0m [4mencoding[24m] [[1m--no-hyphenation[0m][m
       [[1m--no-justification[0m] [[1m-p[0m [4mstring[24m] [[1m-t[0m] [[1m-T[0m[[4mdevice[24m]] [[1m-H[0m[[4mbrowser[24m]] [[1m-X[0m[[4mdpi[24m]] [[1m-Z[0m] [[[4msection[24m][m
       [4mpage[24m ...] ...[m
       [1mman[0m [1m-k[0m [[4mapropos[24m [4moptions[24m] [4mregexp[24m ...[m
       [1mman[0m [1m-K[0m [[1m-w[0m|[1m-W[0m] [[1m-S[0m [4mlist[24m] [[1m-i[0m|[1m-I[0m] [[4m--regex[24m] [[4msection[24m] [4mterm[24m ...[m
       [1mman[0m [1m-f[0m [[4mwhatis[24m [4moptions[24m] [4mpage[24m ...[m
       [1mman[0m  [1m-l[0m  [[1m-C[0m  [4mfile[24m] [[1m-d[0m] [[1m-D[0m] [[1m--warnings[0m[=[4mwarnings[24m]] [[1m-R[0m [4mencoding[24m] [[1m-L[0m [4mlocale[24m] [[1m-P[0m [4mpager[24m][m
       [[1m-r[0m [4mprompt[24m] [[1m-7[0m] [[1m-E[0m [4mencoding[24m] [[1m-p[0m [4mstring[24m] [[1m-t[0m] [[1m-T[0m[[4mdevice[24m]] [[1m-H[0m[[4mbrowser[24m]] [[1m-X[0m[[4mdpi[24m]]  [[1m-Z[0m][m
       [4mfile[24m ...[m
       [1mman[0m [1m-w[0m|[1m-W[0m [[1m-C[0m [4mfile[24m] [[1m-d[0m] [[1m-D[0m] [4mpage[24m ...[m
       [1mman[0m [1m-c[0m [[1m-C[0m [4mfile[24m] [[1m-d[0m] [[1m-D[0m] [4mpage[24m ...[m
       [1mman[0m [[1m-?V[0m][m
[m
[1mDESCRIPTION[0m[m
       [1mman[0m  is the system's manual pager. Each [4mpage[24m argument given to [1mman[0m is normally the name of[m
       a program, utility or function.  The [4mmanual[24m [4mpage[24m associated with each of  these  arguments[m
       is  then found and displayed. A [4msection[24m, if provided, will direct [1mman[0m to look only in that[m
       [4msection[24m of the manual.  The default action is to search in all of the available  [4msections[24m,[m
       following  a  pre-defined order and to show only the first [4mpage[24m found, even if [4mpage[24m exists[m
       in several [4msections[24m.[m
[m
       The table below shows the [4msection[24m numbers of the manual followed by  the  types  of  pages[m
       they contain.[m
[m
       1   Executable programs or shell commands[m
       2   System calls (functions provided by the kernel)[m
       3   Library calls (functions within program libraries)[m
       4   Special files (usually found in [4m/dev[24m)[m
[7m Manual page man(1) line 1 (press h for help or q to quit)[27m[K[K[root@localhost ~]# top
[?25l[?1c[H[J[0;10mtop - 16:14:53 up 20 min,  2 users,  load average: 0.00, 0.01, 0.02[0;10m[39;49m[0;10m[39;49m[K
Tasks:[0;10m[39;49m[1m 117 [0;10m[39;49mtotal,[0;10m[39;49m[1m   1 [0;10m[39;49mrunning,[0;10m[39;49m[1m 116 [0;10m[39;49msleeping,[0;10m[39;49m[1m   0 [0;10m[39;49mstopped,[0;10m[39;49m[1m   0 [0;10m[39;49mzombie[0;10m[39;49m[0;10m[39;49m[K
%Cpu(s):[0;10m[39;49m[1m  0.0 [0;10m[39;49mus,[0;10m[39;49m[1m  1.6 [0;10m[39;49msy,[0;10m[39;49m[1m  0.0 [0;10m[39;49mni,[0;10m[39;49m[1m 98.4 [0;10m[39;49mid,[0;10m[39;49m[1m  0.0 [0;10m[39;49mwa,[0;10m[39;49m[1m  0.0 [0;10m[39;49mhi,[0;10m[39;49m[1m  0.0 [0;10m[39;49msi,[0;10m[39;49m[1m  0.0 [0;10m[39;49mst[0;10m[39;49m[0;10m[39;49m[K
KiB Mem :[0;10m[39;49m[1m  3879732 [0;10m[39;49mtotal,[0;10m[39;49m[1m  3484092 [0;10m[39;49mfree,[0;10m[39;49m[1m   194344 [0;10m[39;49mused,[0;10m[39;49m[1m   201296 [0;10m[39;49mbuff/cache[0;10m[39;49m[0;10m[39;49m[K
KiB Swap:[0;10m[39;49m[1m  2097148 [0;10m[39;49mtotal,[0;10m[39;49m[1m  2097148 [0;10m[39;49mfree,[0;10m[39;49m[1m        0 [0;10m[39;49mused.[0;10m[39;49m[1m  3462112 [0;10m[39;49mavail Mem [0;10m[39;49m[0;10m[39;49m[K
[K
[7m  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                         [0;10m[39;49m[K
[0;10m    1 root      20   0  193672   6732   4160 S   0.0  0.2   0:00.47 systemd                         [0;10m[39;49m[K
[0;10m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd                        [0;10m[39;49m[K
[0;10m    4 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H                    [0;10m[39;49m[K
[0;10m    6 root      20   0       0      0      0 S   0.0  0.0   0:00.03 ksoftirqd/0                     [0;10m[39;49m[K
[0;10m    7 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 migration/0                     [0;10m[39;49m[K
[0;10m    8 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh                          [0;10m[39;49m[K
[0;10m    9 root      20   0       0      0      0 S   0.0  0.0   0:00.18 rcu_sched                       [0;10m[39;49m[K
[0;10m   10 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 lru-add-drain                   [0;10m[39;49m[K
[0;10m   11 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 watchdog/0                      [0;10m[39;49m[K
[0;10m   12 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 watchdog/1                      [0;10m[39;49m[K
[0;10m   13 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 migration/1                     [0;10m[39;49m[K
[0;10m   14 root      20   0       0      0      0 S   0.0  0.0   0:00.00 ksoftirqd/1                     [0;10m[39;49m[K
[0;10m   16 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/1:0H                    [0;10m[39;49m[K
[0;10m   17 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 watchdog/2                      [0;10m[39;49m[K
[0;10m   18 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 migration/2                     [0;10m[39;49m[K
[0;10m   19 root      20   0       0      0      0 S   0.0  0.0   0:00.02 ksoftirqd/2                     [0;10m[39;49m[K
[0;10m   20 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/2:0                     [0;10m[39;49m[K
[0;10m   21 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/2:0H                    [0;10m[39;49m[K
[0;10m   22 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 watchdog/3                      [0;10m[39;49m[K
[0;10m   23 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 migration/3                     [0;10m[39;49m[K
[0;10m   24 root      20   0       0      0      0 S   0.0  0.0   0:00.00 ksoftirqd/3                     [0;10m[39;49m[K
[0;10m   26 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/3:0H                    [0;10m[39;49m[K
[0;10m   28 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kdevtmpfs                       [0;10m[39;49m[K
[0;10m   29 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 netns                           [0;10m[39;49m[K
[0;10m   30 root      20   0       0      0      0 S   0.0  0.0   0:00.00 khungtaskd                      [0;10m[39;49m[K
[0;10m   31 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 writeback                       [0;10m[39;49m[K
[0;10m   32 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kintegrityd                     [0;10m[39;49m[K
[0;10m   33 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset                          [0;10m[39;49m[K
[0;10m   34 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset                          [0;10m[39;49m[K
[0;10m   35 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset                          [0;10m[39;49m[K[38;1H
[?25h[?0c[K[root@localhost ~]# clear
[H[J[root@localhost ~]# exit
exit

Script done on Wed 18 Jan 2023 04:14:59 PM CST
